-- Chạy script này trong Supabase SQL Editor nếu bảng 'friends' chưa xuất hiện:

CREATE TABLE IF NOT EXISTS public.friends (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  friend_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.friends ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their friendships." ON public.friends;
CREATE POLICY "Users can view their friendships."
  ON public.friends FOR SELECT
  USING (auth.uid() = user_id OR auth.uid() = friend_id);

DROP POLICY IF EXISTS "Users can send friend requests." ON public.friends;
CREATE POLICY "Users can send friend requests."
  ON public.friends FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Involved users can update friend request status." ON public.friends;
CREATE POLICY "Involved users can update friend request status."
  ON public.friends FOR UPDATE
  USING (auth.uid() = user_id OR auth.uid() = friend_id);

DROP POLICY IF EXISTS "Involved users can delete friendships/requests." ON public.friends;
CREATE POLICY "Involved users can delete friendships/requests."
  ON public.friends FOR DELETE
  USING (auth.uid() = user_id OR auth.uid() = friend_id);

-- Thêm vào realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.friends;

-- Làm mới schema cache
NOTIFY pgrst, 'reload schema';
