-- ==============================================================================
-- BẢN SỬA ĐỔI HOÀN CHỈNH & CHUẨN XÁC 100% CHO SUPABASE LOCKET CLONE
-- Chạy toàn bộ đoạn mã này trong Supabase Dashboard -> SQL Editor
-- (Có thể chạy lại nhiều lần mà không bị báo lỗi trùng bảng hay trùng publication)
-- ==============================================================================

-- 1. BẢNG THÔNG TIN NGƯỜI DÙNG (Profiles)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  username TEXT UNIQUE,
  avatar_url TEXT
);

-- 2. BẢNG BÀI ĐĂNG (Posts / Ảnh Locket)
CREATE TABLE IF NOT EXISTS public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  image_url TEXT NOT NULL,
  caption TEXT
);

-- 3. BẢNG THẢ CẢM XÚC (Reactions)
CREATE TABLE IF NOT EXISTS public.reactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  emoji TEXT NOT NULL,
  UNIQUE (post_id, user_id, emoji)
);

-- 4. BẢNG TIN NHẮN CHAT (Messages)
-- Lưu ý: receiver_id để trống (NULL) khi chat nhóm Locket Lounge
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  sender_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  receiver_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  text TEXT NOT NULL
);

-- 5. BẢNG BẠN BÈ (Friends - Cực kỳ quan trọng để kết bạn qua User ID)
CREATE TABLE IF NOT EXISTS public.friends (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  friend_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted'))
);

-- ==============================================================================
-- BẬT ROW LEVEL SECURITY (RLS) VÀ CẤP QUYỀN ĐỌC / GHI CHO CÁC BẢNG
-- ==============================================================================

-- Bật RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.friends ENABLE ROW LEVEL SECURITY;

-- Cấp quyền bảng profiles
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Cấp quyền bảng posts
DROP POLICY IF EXISTS "Posts are viewable by everyone" ON public.posts;
CREATE POLICY "Posts are viewable by everyone" ON public.posts FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can insert posts" ON public.posts;
CREATE POLICY "Authenticated users can insert posts" ON public.posts FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Users can delete their own posts" ON public.posts;
CREATE POLICY "Users can delete their own posts" ON public.posts FOR DELETE USING (auth.uid() = user_id);

-- Cấp quyền bảng reactions
DROP POLICY IF EXISTS "Reactions are viewable by everyone" ON public.reactions;
CREATE POLICY "Reactions are viewable by everyone" ON public.reactions FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can manage reactions" ON public.reactions;
CREATE POLICY "Authenticated users can manage reactions" ON public.reactions FOR ALL USING (auth.role() = 'authenticated');

-- Cấp quyền bảng messages
DROP POLICY IF EXISTS "Messages are viewable by everyone" ON public.messages;
CREATE POLICY "Messages are viewable by everyone" ON public.messages FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can insert messages" ON public.messages;
CREATE POLICY "Authenticated users can insert messages" ON public.messages FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Cấp quyền bảng friends
DROP POLICY IF EXISTS "Friends are viewable by involved users" ON public.friends;
CREATE POLICY "Friends are viewable by involved users" ON public.friends FOR ALL USING (true);

-- ==============================================================================
-- BẬT REALTIME CHO CÁC BẢNG (An toàn, không bị lỗi nếu bảng đã có sẵn trong publication)
-- ==============================================================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'messages') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'reactions') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.reactions;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'posts') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.posts;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'friends') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.friends;
  END IF;
END $$;

-- ==============================================================================
-- CẤU HÌNH BUCKET LƯU TRỮ 'locket-images'
-- ==============================================================================

-- 1. Đảm bảo bucket 'locket-images' tồn tại và ở chế độ công khai (Public)
INSERT INTO storage.buckets (id, name, public)
VALUES ('locket-images', 'locket-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- 2. Xóa các policy cũ có thể gây xung đột quyền
DROP POLICY IF EXISTS "Public Access for locket-images" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Users Can Upload to locket-images" ON storage.objects;
DROP POLICY IF EXISTS "Allow All Uploads to locket-images" ON storage.objects;
DROP POLICY IF EXISTS "Allow All Updates to locket-images" ON storage.objects;
DROP POLICY IF EXISTS "Users Can Update Their Own Images in locket-images" ON storage.objects;
DROP POLICY IF EXISTS "locket_images_all_policy" ON storage.objects;

-- 3. Cấp toàn quyền Đọc & Upload cho bucket 'locket-images'
CREATE POLICY "locket_images_all_policy"
ON storage.objects FOR ALL
TO public
USING (bucket_id = 'locket-images')
WITH CHECK (bucket_id = 'locket-images');

-- 4. Tự động đồng bộ và tạo profile cho user (Tránh lỗi foreign key constraint posts_user_id_fkey)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, username, avatar_url)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    null
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Đồng bộ tất cả user đã có sẵn trong auth.users vào bảng profiles
INSERT INTO public.profiles (id, username)
SELECT
  id,
  split_part(email, '@', 1)
FROM auth.users
ON CONFLICT (id) DO NOTHING;

-- 5. Làm mới schema cache của Supabase PostgREST
NOTIFY pgrst, 'reload schema';
